In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
import scipy.linalg as LA
%matplotlib
rng = np.random.default_rng()

from itertools import combinations

Using matplotlib backend: Qt5Agg


In [2]:
n = 3

def print_matrix(matrix):
    for row in matrix:
        print(' '.join(str(int(elem)) for elem in row))

def make_player_move(matrix):
    while True:
        try:
            row1 = int(input('Enter your move (row)')) 
            row = row1 - 1
            col1 = int(input('Enter your move (col)'))
            col = col1 - 1
            if matrix[row, col] == -1:
                matrix[row, col] = 0
                break
            else:
                print("This cell is already taken. Please choose another.")
        except ValueError:
            print("Invalid input. Please enter row and column as two integers separated by a space.")
        except IndexError:
            print("Invalid position. Please make sure the row and column are within the matrix size.")

def make_computer_move(matrix):
    empty_cells = [(row, col) for row in range(matrix.shape[0]) for col in range(matrix.shape[1]) if matrix[row, col] == -1]
    if empty_cells:
        move = random.choice(empty_cells)
        matrix[move] = 1
        print(f"Computer placed a '1' in position {move}")

def check_game_end(matrix):
    return np.all(matrix != -1)

def play_game(n):
    # Initialize the matrix with -1 to indicate empty cells
    matrix = np.full((n, n), -1, dtype=int)

    while not check_game_end(matrix):
        print("\nCurrent board:")
        print_matrix(matrix)
        make_player_move(matrix)
        if check_game_end(matrix):
            break
        make_computer_move(matrix)

    print("\nFinal board:")
    print_matrix(matrix)
    determinant = np.linalg.det(matrix)
    if determinant == 0:
        print("Congratulations! You win. The determinant of the matrix is zero.")
    else:
        print(f"Game over. The determinant of the matrix is {determinant}. You lose.")
        
play_game(n)


Current board:
-1 -1 -1
-1 -1 -1
-1 -1 -1
Enter your move (row)1
Enter your move (col)1
Computer placed a '1' in position (1, 0)

Current board:
0 -1 -1
1 -1 -1
-1 -1 -1
Enter your move (row)1
Enter your move (col)2
Computer placed a '1' in position (1, 2)

Current board:
0 0 -1
1 -1 1
-1 -1 -1
Enter your move (row)1
Enter your move (col)2
This cell is already taken. Please choose another.
Enter your move (row)1
Enter your move (col)3
Computer placed a '1' in position (2, 1)

Current board:
0 0 0
1 -1 1
-1 1 -1
Enter your move (row)3
Enter your move (col)3
Computer placed a '1' in position (2, 0)

Current board:
0 0 0
1 -1 1
1 1 0
Enter your move (row)2
Enter your move (col)2

Final board:
0 0 0
1 0 1
1 1 0
Congratulations! You win. The determinant of the matrix is zero.


In [ ]:
combos = list(combinations(range(9), 4))

# Loop through each combination
for combo in combos:
    # Reset the matrix for each combination
    matrix = np.zeros((3, 3))
    count = 0

    # Place "1"s according to the current combination
    for pos in combo:
        row, col = divmod(pos, 3)  # Convert the 1D position to 2D (row, col) indices
        matrix[row, col] = 1

    # Calculate the determinant of the matrix
    determinant = np.linalg.det(matrix)
    if determinant == 0:
        count += 1
    
    # Count the number of zeros in the matrix
    zero_count = np.count_nonzero(matrix == 0)
    
    # Print the combination and the corresponding matrix and its determinant
    print("Combination:", combo)
    print(matrix)
    print("Determinant:", determinant)
    print("---")  # Separator for readability
print(count)

In [3]:
# Generate all combinations for choosing 4 out of 9 items
combos = list(combinations(range(9), 4))

zero_determinant_count = 0

for combo in combos:
    matrix = np.zeros((3, 3))

    # Place "1"s according to the current combination
    for pos in combo:
        row, col = divmod(pos, 3)  # Convert the 1D position to 2D (row, col) indices
        matrix[row, col] = 1

    determinant = np.linalg.det(matrix)
    
    # Check if the determinant is 0 and increment the counter if so
    if determinant == 0:
        zero_determinant_count += 1
    
    # Count the number of zeros in the matrix
    zero_count = np.count_nonzero(matrix == 0)

    print("Combination:", combo)
    print(matrix)
    print("Determinant:", determinant)
    print("---") 
zero_determinant_count

Combination: (0, 1, 2, 3)
[[1. 1. 1.]
 [1. 0. 0.]
 [0. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 4)
[[1. 1. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 5)
[[1. 1. 1.]
 [0. 0. 1.]
 [0. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 6)
[[1. 1. 1.]
 [0. 0. 0.]
 [1. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 7)
[[1. 1. 1.]
 [0. 0. 0.]
 [0. 1. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 8)
[[1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 1.]]
Determinant: 0.0
---
Combination: (0, 1, 3, 4)
[[1. 1. 0.]
 [1. 1. 0.]
 [0. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 3, 5)
[[1. 1. 0.]
 [1. 0. 1.]
 [0. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 3, 6)
[[1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 3, 7)
[[1. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 3, 8)
[[1. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
Determinant: -1.0
---
Combination: (0, 1, 4, 5)
[[1. 1. 0.]
 [0. 1. 1.]
 [0. 0. 0.]]
Determinant:

90

In [4]:
# Generate all combinations for choosing 5 out of 9 items
combos1 = list(combinations(range(9), 5))

count1 = 0

for combo in combos1:
    matrix1 = np.zeros((3, 3))

    # Place "1"s according to the current combination
    for pos in combo:
        row, col = divmod(pos, 3)  # Convert the 1D position to 2D (row, col) indices
        matrix1[row, col] = 1

    determinant = np.linalg.det(matrix1)
    
    # Check if the determinant is 0 and increment the counter if so
    if determinant == 0:
        count1 += 1

    print("Combination:", combo)
    print(matrix1)
    print("Determinant:", determinant)
    print("---") 
count1

Combination: (0, 1, 2, 3, 4)
[[1. 1. 1.]
 [1. 1. 0.]
 [0. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 3, 5)
[[1. 1. 1.]
 [1. 0. 1.]
 [0. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 3, 6)
[[1. 1. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 3, 7)
[[1. 1. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Determinant: 1.0
---
Combination: (0, 1, 2, 3, 8)
[[1. 1. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
Determinant: -1.0
---
Combination: (0, 1, 2, 4, 5)
[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 4, 6)
[[1. 1. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Determinant: -1.0
---
Combination: (0, 1, 2, 4, 7)
[[1. 1. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 4, 8)
[[1. 1. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
Determinant: 1.0
---
Combination: (0, 1, 2, 5, 6)
[[1. 1. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]
Determinant: 1.0
---
Combination: (0, 1, 2, 5, 7)
[[1. 1. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]
Determinant: -1.0
---
Combination: (0, 1, 2, 5, 8)
[[1. 1. 1.]

54

In [5]:
combos2 = list(combinations(range(16), 8))
count2 = 0

# Loop through each combination
for combo in combos2:
    # Reset the matrix for each combination
    matrix2 = np.zeros((4, 4))
    
    # Place "1"s according to the current combination
    for pos in combo:
        row, col = divmod(pos, 4)  # Convert the 1D position to 2D (row, col) indices
        matrix2[row, col] = 1

    # Calculate the determinant of the matrix
    determinant = np.linalg.det(matrix2)
    if determinant == 0:
        count2 += 1
    
    # Count the number of zeros in the matrix
    zero_count = np.count_nonzero(matrix == 0)
    
    # Print the combination and the corresponding matrix and its determinant
    print("Combination:", combo)
    print(matrix2)
    print("Determinant:", determinant)
    print("---")  # Separator for readability
print(count2)

Combination: (0, 1, 2, 3, 4, 5, 6, 7)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 3, 4, 5, 6, 8)
[[1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 3, 4, 5, 6, 9)
[[1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 3, 4, 5, 6, 10)
[[1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 3, 4, 5, 6, 11)
[[1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 3, 4, 5, 6, 12)
[[1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 3, 4, 5, 6, 13)
[[1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 3, 4, 5, 6, 14)
[[1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]]
Determinant: 0.0
---
Combination: (0, 1, 2, 3, 4, 5, 6, 